DROP TABLE IF EXISTS Collaborateur ;
DROP TABLE IF EXISTS Administrateur ;
DROP TABLE IF EXISTS DROITS ;
DROP TABLE IF EXISTS Salle ;
DROP TABLE IF EXISTS MESSAGE ;
DROP TABLE IF EXISTS ETRE ;

CREATE TABLE Collaborateur(
	idCollab SERIAL NOT NULL,
	nomCollab VARCHAR,
	prenomCollab VARCHAR,
	pseudoCollab VARCHAR,
	mailCollab VARCHAR(50),
	mdpCollab VARCHAR(50),
	
	PRIMARY KEY (idCollab)
);

CREATE TABLE Administrateur (
	idAdmin SERIAL   NOT NULL,
	
	PRIMARY KEY (idAdmin) 
);

CREATE TABLE DROITS (
	idDroit SERIAL   NOT NULL,
	descriptionDroit VARCHAR(20),
	ecriture BOOL,
	lecture BOOL,
	changerDescSalon BOOL,
	
	PRIMARY KEY (idDroit)
);

CREATE TABLE Salle (
	idSalle SERIAL NOT NULL,
	type VARCHAR,
	descrSalle VARCHAR(50),
	titreSalle VARCHAR(50),
	dateCreaSalle DATE,

	PRIMARY KEY (idSalle)
);

CREATE TABLE MESSAGE (
	idMessage SERIAL NOT NULL,
	contenu VARCHAR(500),
	dateEnvoi DATE,
	heureEnvoi VARCHAR(20),
	afficheDansSalon BOOL,
	PRIMARY KEY (idMessage) ) ;

CREATE TABLE ETRE (idCollab BIGINT   NOT NULL,
idAdmin INT NOT NULL,
PRIMARY KEY (idCollab,
 idAdmin) ) ;

DROP TABLE IF EXISTS AVOIR_DROITS_DANS_SALLE ;
CREATE TABLE AVOIR_DROITS_DANS_SALLE (idCollab BIGINT   NOT NULL,
idDroit BIGINT NOT NULL,
idSalle BIGINT NOT NULL,
PRIMARY KEY (idCollab,
 idDroit,
 idSalle) ) ;

DROP TABLE IF EXISTS CREER ;
CREATE TABLE CREER (idAdmin INT   NOT NULL,
idSalle BIGINT NOT NULL,
PRIMARY KEY (idAdmin,
 idSalle) ) ;

DROP TABLE IF EXISTS AFFECTER ;
CREATE TABLE AFFECTER (idAdmin INT   NOT NULL,
idSalle BIGINT NOT NULL,
idCollab BIGINT NOT NULL,
PRIMARY KEY (idAdmin,
 idSalle,
 idCollab) ) ;

DROP TABLE IF EXISTS SE_CONNECTER ;
CREATE TABLE SE_CONNECTER (idCollab BIGINT   NOT NULL,
idSalle BIGINT NOT NULL,
PRIMARY KEY (idCollab,
 idSalle) ) ;

DROP TABLE IF EXISTS ENVOYER ;
CREATE TABLE ENVOYER (idCollab BIGINT   NOT NULL,
idMessage BIGINT NOT NULL,
idSalle BIGINT NOT NULL,
PRIMARY KEY (idCollab,
 idMessage,
 idSalle) ) ;

ALTER TABLE ETRE ADD CONSTRAINT FK_ETRE_idCollab FOREIGN KEY (idCollab) REFERENCES Collaborateur (idCollab);

ALTER TABLE ETRE ADD CONSTRAINT FK_ETRE_idAdmin FOREIGN KEY (idAdmin) REFERENCES Administrateur (idAdmin);
ALTER TABLE AVOIR_DROITS_DANS_SALLE ADD CONSTRAINT FK_AVOIR_DROITS_DANS_SALLE_idCollab FOREIGN KEY (idCollab) REFERENCES Collaborateur (idCollab);
ALTER TABLE AVOIR_DROITS_DANS_SALLE ADD CONSTRAINT FK_AVOIR_DROITS_DANS_SALLE_idDroit FOREIGN KEY (idDroit) REFERENCES DROITS (idDroit);
ALTER TABLE AVOIR_DROITS_DANS_SALLE ADD CONSTRAINT FK_AVOIR_DROITS_DANS_SALLE_idSalle FOREIGN KEY (idSalle) REFERENCES Salle (idSalle);
ALTER TABLE CREER ADD CONSTRAINT FK_CREER_idAdmin FOREIGN KEY (idAdmin) REFERENCES Administrateur (idAdmin);
ALTER TABLE CREER ADD CONSTRAINT FK_CREER_idSalle FOREIGN KEY (idSalle) REFERENCES Salle (idSalle);
ALTER TABLE AFFECTER ADD CONSTRAINT FK_AFFECTER_idAdmin FOREIGN KEY (idAdmin) REFERENCES Administrateur (idAdmin);
ALTER TABLE AFFECTER ADD CONSTRAINT FK_AFFECTER_idSalle FOREIGN KEY (idSalle) REFERENCES Salle (idSalle);
ALTER TABLE AFFECTER ADD CONSTRAINT FK_AFFECTER_idCollab FOREIGN KEY (idCollab) REFERENCES Collaborateur (idCollab);
ALTER TABLE SE_CONNECTER ADD CONSTRAINT FK_SE_CONNECTER_idCollab FOREIGN KEY (idCollab) REFERENCES Collaborateur (idCollab);
ALTER TABLE SE_CONNECTER ADD CONSTRAINT FK_SE_CONNECTER_idSalle FOREIGN KEY (idSalle) REFERENCES Salle (idSalle);
ALTER TABLE ENVOYER ADD CONSTRAINT FK_ENVOYER_idCollab FOREIGN KEY (idCollab) REFERENCES Collaborateur (idCollab);
ALTER TABLE ENVOYER ADD CONSTRAINT FK_ENVOYER_idMessage FOREIGN KEY (idMessage) REFERENCES MESSAGE (idMessage);
ALTER TABLE ENVOYER ADD CONSTRAINT FK_ENVOYER_idSalle FOREIGN KEY (idSalle) REFERENCES Salle (idSalle);
