INSERT INTO Collaborateur VALUES(1,'Aoun','Andre','aoun','aoun@irit.fr','mdp');
INSERT INTO Collaborateur VALUES(2,'Desprats','Thierry','desprats','desprats@irit.fr','mdp');

INSERT INTO Administrateur VALUES(1);

INSERT INTO ETRE VALUES(1,1);

INSERT INTO MESSAGE VALUES(1,'Il faudrait annuler la réunion de demain','2016/05/27','09:00','1');
INSERT INTO MESSAGE VALUES(2,'Ça marche!','2016/05/27','09:18','1');

INSERT INTO Salle VALUES(1,'Public','Discussion Enseignants STRI','STRI','2016/05/26');
INSERT INTO Salle VALUES(2,'Private','Discussion Enseignants STRI en mode privé','STRI_VIP','2016/05/31');

INSERT INTO DROITS VALUES(1,'Droit admin','1','1','1');
INSERT INTO DROITS VALUES(2,'Droit normal','0','1','0');
INSERT INTO DROITS VALUES(3,'Droit restreint','0','0','0');

INSERT INTO AVOIR_DROITS_DANS_SALLE VALUES(1,1,1);
INSERT INTO AVOIR_DROITS_DANS_SALLE VALUES(2,2,1);
INSERT INTO AVOIR_DROITS_DANS_SALLE VALUES(1,1,2);
INSERT INTO AVOIR_DROITS_DANS_SALLE VALUES(2,2,2);

INSERT INTO CREER VALUES(1,1);
INSERT INTO CREER VALUES(1,2);

INSERT INTO AFFECTER VALUES(1,1,1);
INSERT INTO AFFECTER VALUES(1,1,2);
INSERT INTO AFFECTER VALUES(1,2,1);
INSERT INTO AFFECTER VALUES(1,2,2);

INSERT INTO SE_CONNECTER VALUES(1,1,'Online');
INSERT INTO SE_CONNECTER VALUES(2,1,'Online');

INSERT INTO ENVOYER VALUES(1,1,1);
INSERT INTO ENVOYER VALUES(2,2,1);
