/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.delgadopereira.projetjavaswing;

/**
 *
 * @author Delgado Pereira
 */
public class IHM_Main extends javax.swing.JFrame {

    ExecBD e;
    
    /**
     * Creates new form IHM_Main
     * @param service
     * @param e
     */
    public IHM_Main(boolean service,ExecBD e) {
        initComponents();
        String s;
        
        connection_status.setText("");
        
        if (service){
            s = "Actif";
        }
        else{
            s = "Hors service";
        }
        label_etat_du_service.setText("Etat du service: " + s);
        text_identifiant.setText("Veuillez écrire votre identifiant");
        text_mdp.setText("password");
        
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_identifiant = new javax.swing.JTextField();
        text_mdp = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label_etat_du_service = new javax.swing.JLabel();
        connection_status = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Delgado Pereira\\Downloads\\STRI-logo-OK2.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Bienvenue au Chat STRI !");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Identifiant:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mot de passe:");

        text_identifiant.setText("jTextField1");
        text_identifiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_identifiantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                text_identifiantMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                text_identifiantMouseExited(evt);
            }
        });
        text_identifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_identifiantActionPerformed(evt);
            }
        });

        text_mdp.setText("jPasswordField1");
        text_mdp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                text_mdpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                text_mdpMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Veuillez vous identifier:");

        jButton1.setText("Se connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label_etat_du_service.setText("Etat du service:");

        connection_status.setForeground(new java.awt.Color(255, 0, 0));
        connection_status.setText("jLabel6");
        connection_status.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label_etat_du_service)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(28, 28, 28))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(connection_status)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(text_mdp, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                                            .addComponent(text_identifiant)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jButton1)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(text_identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(connection_status)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(label_etat_du_service)
                .addGap(23, 23, 23))
        );

        jMenu1.setText("Fichier");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Aide");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        se_connecter();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void text_identifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_identifiantActionPerformed
        
    }//GEN-LAST:event_text_identifiantActionPerformed

    private void text_identifiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_identifiantMouseClicked
        text_identifiant.setText("");
    }//GEN-LAST:event_text_identifiantMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        text_identifiant.setText("Veuillez écrire votre identifiant");
    }//GEN-LAST:event_jPanel1MouseClicked

    private void text_mdpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_mdpMouseEntered
        char[] mdp = text_mdp.getPassword();
                
        if (Main.charToString(mdp).equals("password"))
            text_mdp.setText("");
    }//GEN-LAST:event_text_mdpMouseEntered

    private void text_identifiantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_identifiantMouseEntered
        if (text_identifiant.getText().equals("") 
                || text_identifiant.getText().
                        equals("Veuillez écrire votre identifiant")){

            text_identifiant.setText("");
        }
    }//GEN-LAST:event_text_identifiantMouseEntered

    private void text_identifiantMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_identifiantMouseExited
        if (text_identifiant.getText().equals("")){
            text_identifiant.setText("Veuillez écrire votre identifiant");
        }
    }//GEN-LAST:event_text_identifiantMouseExited

    private void text_mdpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_mdpMouseExited
        if (text_mdp.getPassword().equals("")){
            text_mdp.setText("password");
        }
    }//GEN-LAST:event_text_mdpMouseExited

    private void se_connecter(){
        String id;
        char[] mdp;
        
        id = text_identifiant.getText();
        mdp = text_mdp.getPassword();
        
        String s_mdp = Main.charToString(mdp);
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Integer userType = Utilisateur.verifier(id, s_mdp, this.e);  
        
        if (userType != null){
            this.setVisible(false);
            IHM.charger(userType);
        }
        else{
            connection_status.setText("identifiant ou mot de passe Erroné");
        }        
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connection_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_etat_du_service;
    private javax.swing.JTextField text_identifiant;
    private javax.swing.JPasswordField text_mdp;
    // End of variables declaration//GEN-END:variables
}
